name: Build and push :master image

on:
  push:
    branches:
      - backport-cbc-cipher-deprecation-to-v1.7.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Push to registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        REGISTRY: alfatraining
        VERSION: v1.7.0
        TAG_LATEST: "false"
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        make push
        docker logout
